fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: name-tests-test
        args: [ "--django" ]
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/autoflake
    rev:  v2.0.0
    hooks:
      - id: autoflake
        name: Remove unused variables and imports
        language: python
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--ignore-init-module-imports",
          ]
        files: \.py$


  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [ '-iii', '-ll' ]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/pylint
    rev: "v2.13.0"
    hooks:
      - id: pylint
        language: system
        types: [python]
        args: [
          "-rn", # Only display messages
          "--rcfile=./.pylintrc", # Link to your config file,
        ]
        exclude: "[a-zA-Z]*/(migrations)/(.)*"


  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
    -   id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell --ignore-words ignore-spelling-words.txt readme.md
        language: python
        types: [text]
